// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj7JhBpAwONSKnl98cZB4kLgER45tCn54',
    appId: '1:24247089008:web:e5aeb477bea7e86b8241b5',
    messagingSenderId: '24247089008',
    projectId: 'findyourinvestor-fyi',
    authDomain: 'findyourinvestor-fyi.firebaseapp.com',
    storageBucket: 'findyourinvestor-fyi.appspot.com',
    measurementId: 'G-S71W0WRW6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhrYyaIuh8TVfIG8lnH8HDZD_DILwe7s',
    appId: '1:24247089008:android:5f7725fe6361f3eb8241b5',
    messagingSenderId: '24247089008',
    projectId: 'findyourinvestor-fyi',
    storageBucket: 'findyourinvestor-fyi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqLsvh618kH6tdOlZJBwvbcvdU6luvoCQ',
    appId: '1:24247089008:ios:225ffcae33d22fac8241b5',
    messagingSenderId: '24247089008',
    projectId: 'findyourinvestor-fyi',
    storageBucket: 'findyourinvestor-fyi.appspot.com',
    iosClientId: '24247089008-jnr5sevh3ik1j0e3ah132ferb8pp49pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqLsvh618kH6tdOlZJBwvbcvdU6luvoCQ',
    appId: '1:24247089008:ios:225ffcae33d22fac8241b5',
    messagingSenderId: '24247089008',
    projectId: 'findyourinvestor-fyi',
    storageBucket: 'findyourinvestor-fyi.appspot.com',
    iosClientId: '24247089008-jnr5sevh3ik1j0e3ah132ferb8pp49pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyi',
  );
}
